"""
Generator for Gaussian External calculator scripts using ASE.

This module provides:

- ``GaussianExternalInput``: parses Gaussian's External input file format.
- ``ASEExternalCalculatorScript``: generates a script from a calculator class.
- ``ASEPickleExternalScript``: generates a script from a calculator instance
  via pickle serialisation.

Gaussian External interface
---------------------------
Gaussian calls the script as::

    <script> [extra_args] layer InputFile OutputFile MsgFile FChkFile MatElFile

The six standard parameters are always the **last** six arguments.

Input file format (all values in atomic units)::

    natoms  deriv_order  charge  spin          (4I10)
    atomic_num  x  y  z  mm_charge            (I10, 4F20.12) × natoms

  - Positions in Bohr.
  - deriv_order: 0 = energy only, 1 = energy + gradient.

Output file format (all values in atomic units)::

    energy  dip_x  dip_y  dip_z              (4D20.12)
    dE/dX   dE/dY  dE/dZ                     (3D20.12) × natoms  [if deriv≥1]

  - Energy in Hartree.
  - Dipole in Debye (may be zero).
  - Gradient (dE/dX) in Hartree/Bohr; note gradient = −force.
"""

import inspect
import logging
import os
import stat
import textwrap

logger = logging.getLogger(__name__)

_BOHR_TO_ANG = 0.529177210903
_EV_PER_HA = 27.211386245988
_GRAD_CONV = _BOHR_TO_ANG / _EV_PER_HA  # multiply eV/Å gradient by this


class GaussianExternalInput:
    """
    Parses a Gaussian External input file.

    Gaussian writes the input file in the format::

        natoms  deriv_order  charge  spin          (4I10)
        atomic_num  x  y  z  mm_charge            (I10, 4F20.12) × natoms

    Positions are in Bohr; this class converts them to Angstrom on read.

    Parameters
    ----------
    filename : str
        Path to the Gaussian External input file to parse.

    Attributes
    ----------
    natoms : int
        Number of atoms.
    deriv_order : int
        Derivative order (0 = energy only, 1 = energy + gradient).
    charge : int
        Molecular charge.
    spin : int
        Spin multiplicity.
    atomic_numbers : list of int
        Atomic numbers for each atom.
    positions_ang : list of [float, float, float]
        Cartesian positions in Angstrom.
    """

    BOHR_TO_ANG = _BOHR_TO_ANG

    def __init__(self, filename):
        with open(filename) as fh:
            lines = fh.readlines()
        header = lines[0].split()
        self.natoms = int(header[0])
        self.deriv_order = int(header[1])
        self.charge = int(header[2])
        self.spin = int(header[3])
        self.atomic_numbers = []
        self.positions_ang = []
        for line in lines[1 : self.natoms + 1]:
            parts = line.split()
            self.atomic_numbers.append(int(parts[0]))
            self.positions_ang.append(
                [
                    float(parts[1]) * self.BOHR_TO_ANG,
                    float(parts[2]) * self.BOHR_TO_ANG,
                    float(parts[3]) * self.BOHR_TO_ANG,
                ]
            )


_SCRIPT_TEMPLATE = textwrap.dedent(
    '''\
    #!/usr/bin/env python
    """
    Gaussian External calculator script — generated by chemsmart.

    Invocation::

        {script_name} [extra_args] layer InputFile OutputFile MsgFile FChkFile MatElFile

    The six standard Gaussian External parameters are always the last six
    arguments.  Any leading arguments are ignored (they are consumed by
    Gaussian's External dispatch mechanism).
    """

    import sys
    import os

    import numpy as np
    from ase import Atoms
    {calc_import}
    from chemsmart.io.gaussian.external_script import GaussianExternalInput

    EV_PER_HA = 27.211386245988
    BOHR_TO_ANG = GaussianExternalInput.BOHR_TO_ANG
    GRAD_CONV = BOHR_TO_ANG / EV_PER_HA


    def _write_output(filename, energy_ha, gradient_ha_bohr=None):
        """
        Write a Gaussian External output file (energy + optional gradient).

        Parameters
        ----------
        filename : str
            Path to the output file Gaussian will read.
        energy_ha : float
            Total energy in Hartree.
        gradient_ha_bohr : array-like or None
            Gradient (dE/dX) in Hartree/Bohr, shape (natoms, 3).
            Note: gradient = −force.  Pass None for energy-only jobs.
        """
        with open(filename, "w") as fh:
            fh.write(
                f"{{energy_ha:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}\\n"
            )
            if gradient_ha_bohr is not None:
                for gx, gy, gz in gradient_ha_bohr:
                    fh.write(f"{{gx:20.12E}}{{gy:20.12E}}{{gz:20.12E}}\\n")


    def main():
        if len(sys.argv) < 7:
            sys.stderr.write(
                f"Usage: {{sys.argv[0]}} [extra_args] "
                "layer InputFile OutputFile MsgFile FChkFile MatElFile\\n"
            )
            sys.exit(1)

        _layer = sys.argv[-6]
        input_file = sys.argv[-5]
        output_file = sys.argv[-4]
        msg_file = sys.argv[-3]

        try:
            inp = GaussianExternalInput(input_file)
            atoms = Atoms(numbers=inp.atomic_numbers, positions=inp.positions_ang)

            {calc_init}
            atoms.calc = calc

            energy_ev = atoms.get_potential_energy()
            energy_ha = energy_ev / EV_PER_HA

            gradient_ha_bohr = None
            if inp.deriv_order >= 1:
                forces_ev_ang = atoms.get_forces()
                gradient_ha_bohr = -forces_ev_ang * GRAD_CONV

            _write_output(output_file, energy_ha, gradient_ha_bohr)

            with open(msg_file, "w") as fh:
                fh.write(
                    f"{calc_class_name} completed. "
                    f"Energy = {{energy_ha:.8f}} Ha\\n"
                )

        except Exception:
            import traceback

            with open(msg_file, "w") as fh:
                fh.write(
                    "ERROR in Gaussian External ASE script:\\n"
                    + traceback.format_exc()
                )
            raise


    if __name__ == "__main__":
        main()
    '''
)

_PICKLE_TEMPLATE = textwrap.dedent(
    '''\
    #!/usr/bin/env python
    """
    Gaussian External calculator script (pickle-based) — generated by chemsmart.
    """

    import sys
    import os
    import pickle

    import numpy as np
    from ase import Atoms
    from chemsmart.io.gaussian.external_script import GaussianExternalInput

    EV_PER_HA = 27.211386245988
    BOHR_TO_ANG = GaussianExternalInput.BOHR_TO_ANG
    GRAD_CONV = BOHR_TO_ANG / EV_PER_HA

    _PICKLE_FILE = os.path.join(os.path.dirname(__file__), "{pickle_name}")


    def _write_output(filename, energy_ha, gradient_ha_bohr=None):
        with open(filename, "w") as fh:
            fh.write(
                f"{{energy_ha:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}{{0.0:20.12E}}\\n"
            )
            if gradient_ha_bohr is not None:
                for gx, gy, gz in gradient_ha_bohr:
                    fh.write(f"{{gx:20.12E}}{{gy:20.12E}}{{gz:20.12E}}\\n")


    def main():
        if len(sys.argv) < 7:
            sys.stderr.write(
                f"Usage: {{sys.argv[0]}} [extra_args] "
                "layer InputFile OutputFile MsgFile FChkFile MatElFile\\n"
            )
            sys.exit(1)

        _layer = sys.argv[-6]
        input_file = sys.argv[-5]
        output_file = sys.argv[-4]
        msg_file = sys.argv[-3]

        try:
            inp = GaussianExternalInput(input_file)
            atoms = Atoms(numbers=inp.atomic_numbers, positions=inp.positions_ang)

            with open(_PICKLE_FILE, "rb") as fh:
                calc = pickle.load(fh)
            atoms.calc = calc

            energy_ev = atoms.get_potential_energy()
            energy_ha = energy_ev / EV_PER_HA

            gradient_ha_bohr = None
            if inp.deriv_order >= 1:
                forces_ev_ang = atoms.get_forces()
                gradient_ha_bohr = -forces_ev_ang * GRAD_CONV

            _write_output(output_file, energy_ha, gradient_ha_bohr)

            with open(msg_file, "w") as fh:
                fh.write(f"ASE calculator completed. Energy = {{energy_ha:.8f}} Ha\\n")

        except Exception:
            import traceback

            with open(msg_file, "w") as fh:
                fh.write(
                    "ERROR in Gaussian External ASE script:\\n"
                    + traceback.format_exc()
                )
            raise


    if __name__ == "__main__":
        main()
    '''
)


class ASEExternalCalculatorScript:
    """
    Generates a Gaussian External script from an ASE calculator *class*.

    The generated script is a self-contained Python file that Gaussian calls
    during energy/force evaluations.  It imports and instantiates the
    calculator class by name, making the output human-readable and editable.

    Parameters
    ----------
    calculator_class : type
        An ASE calculator class (not an instance).
    calc_kwargs : dict
        Keyword arguments passed to the calculator constructor in the
        generated script.

    Examples
    --------
    ::

        from mace.calculators import MACECalculator
        script = ASEExternalCalculatorScript(
            MACECalculator,
            calc_kwargs={"model_paths": ["model.model"], "device": "cpu"},
        )
        script.write("/path/to/job/dir", "run_mace.py")
    """

    def __init__(self, calculator_class, calc_kwargs):
        if not inspect.isclass(calculator_class):
            raise TypeError(
                "calculator_class must be a class. "
                "To use a calculator instance, use ASEPickleExternalScript."
            )
        if calc_kwargs is None:
            raise ValueError(
                "calc_kwargs is required when passing a calculator class. "
                "Provide the constructor arguments as a dict."
            )
        self._calc_module = calculator_class.__module__
        self._calc_class_name = calculator_class.__name__
        self.calc_kwargs = calc_kwargs

    def write(self, directory, filename):
        """
        Write the external calculator script.

        The script is made executable (``chmod +x``).

        Parameters
        ----------
        directory : str
            Directory in which to write the file.
        filename : str
            Name of the script file (e.g. ``"run_mace.py"``).

        Returns
        -------
        str
            Absolute path to the written script.
        """
        os.makedirs(directory, exist_ok=True)
        script_path = os.path.join(directory, filename)
        content = self._generate_script(filename)
        with open(script_path, "w") as fh:
            fh.write(content)
        current = os.stat(script_path).st_mode
        os.chmod(script_path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        logger.info(f"Wrote Gaussian External script: {script_path}")
        return os.path.abspath(script_path)

    def _generate_script(self, filename):
        """Return the complete script content as a string."""
        calc_import = (
            f"from {self._calc_module} import {self._calc_class_name}"
        )
        calc_init = f"calc = {self._calc_class_name}(**{self.calc_kwargs!r})"
        return _SCRIPT_TEMPLATE.format(
            script_name=filename,
            calc_import=calc_import,
            calc_init=calc_init,
            calc_class_name=self._calc_class_name,
        )


class ASEPickleExternalScript:
    """
    Generates a Gaussian External script from an ASE calculator *instance*
    via pickle serialisation.

    Use this class when the calculator cannot be reconstructed from a
    plain import + constructor call (e.g. it holds trained model weights
    in memory and does not implement ``todict()``).

    An additional ``<base>.pkl`` file is written alongside the script and
    loaded at runtime by the generated script.

    Parameters
    ----------
    calculator : ASE Calculator instance
        An instantiated calculator to serialise.

    Examples
    --------
    ::

        calc = SomeExoticCalculator(param=42)
        script = ASEPickleExternalScript(calc)
        script.write("/path/to/job/dir", "run_exotic.py")
    """

    def __init__(self, calculator):
        if inspect.isclass(calculator):
            raise TypeError(
                "calculator must be an instance, not a class. "
                "To use a calculator class, use ASEExternalCalculatorScript."
            )
        import pickle

        self._pickle_bytes = pickle.dumps(calculator)

    def write(self, directory, filename):
        """
        Write the pickle-based external calculator script and ``.pkl`` file.

        The script is made executable (``chmod +x``).

        Parameters
        ----------
        directory : str
            Directory in which to write the files.
        filename : str
            Name of the script file (e.g. ``"run_exotic.py"``).

        Returns
        -------
        str
            Absolute path to the written script.
        """
        os.makedirs(directory, exist_ok=True)
        script_path = os.path.join(directory, filename)
        base = os.path.splitext(filename)[0]
        pickle_name = base + ".pkl"
        content = _PICKLE_TEMPLATE.format(pickle_name=pickle_name)
        with open(script_path, "w") as fh:
            fh.write(content)
        current = os.stat(script_path).st_mode
        os.chmod(script_path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        logger.info(f"Wrote Gaussian External pickle script: {script_path}")

        pickle_path = os.path.join(directory, pickle_name)
        with open(pickle_path, "wb") as fh:
            fh.write(self._pickle_bytes)
        logger.info(f"Wrote calculator pickle: {pickle_path}")

        return os.path.abspath(script_path)
